// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SmartGrowHub.Infrastructure.Data.CompiledModels
{
    public partial class ApplicationContextModel
    {
        private ApplicationContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("3999d3e9-0479-4dcb-9e9b-5a721a3a1e6a"), entityTypeCount: 8)
        {
        }

        partial void Initialize()
        {
            var componentDb = ComponentDbEntityType.Create(this);
            var growHubDb = GrowHubDbEntityType.Create(this);
            var oneTimePasswordDb = OneTimePasswordDbEntityType.Create(this);
            var plantDb = PlantDbEntityType.Create(this);
            var sensorReadingDb = SensorReadingDbEntityType.Create(this);
            var settingDb = SettingDbEntityType.Create(this);
            var userDb = UserDbEntityType.Create(this);
            var userSessionDb = UserSessionDbEntityType.Create(this);

            ComponentDbEntityType.CreateForeignKey1(componentDb, settingDb);
            GrowHubDbEntityType.CreateForeignKey1(growHubDb, plantDb);
            GrowHubDbEntityType.CreateForeignKey2(growHubDb, userDb);
            OneTimePasswordDbEntityType.CreateForeignKey1(oneTimePasswordDb, userDb);
            SensorReadingDbEntityType.CreateForeignKey1(sensorReadingDb, growHubDb);
            SettingDbEntityType.CreateForeignKey1(settingDb, growHubDb);
            UserSessionDbEntityType.CreateForeignKey1(userSessionDb, userDb);

            ComponentDbEntityType.CreateAnnotations(componentDb);
            GrowHubDbEntityType.CreateAnnotations(growHubDb);
            OneTimePasswordDbEntityType.CreateAnnotations(oneTimePasswordDb);
            PlantDbEntityType.CreateAnnotations(plantDb);
            SensorReadingDbEntityType.CreateAnnotations(sensorReadingDb);
            SettingDbEntityType.CreateAnnotations(settingDb);
            UserDbEntityType.CreateAnnotations(userDb);
            UserSessionDbEntityType.CreateAnnotations(userSessionDb);

            AddAnnotation("ProductVersion", "9.0.0");
        }
    }
}
