// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SmartGrowHub.Infrastructure.Data.CompiledModels
{
    public partial class ApplicationContextModel
    {
        private ApplicationContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("fed9d810-eb22-40dd-bbf2-a308e6e3ed6f"), entityTypeCount: 9)
        {
        }

        partial void Initialize()
        {
            var growHubDb = GrowHubDbEntityType.Create(this);
            var growHubModuleDb = GrowHubModuleDbEntityType.Create(this);
            var moduleProgramDb = ModuleProgramDbEntityType.Create(this);
            var oneTimePasswordDb = OneTimePasswordDbEntityType.Create(this);
            var plantDb = PlantDbEntityType.Create(this);
            var sensorReadingDb = SensorReadingDbEntityType.Create(this);
            var timedQuantityDb = TimedQuantityDbEntityType.Create(this);
            var userDb = UserDbEntityType.Create(this);
            var userSessionDb = UserSessionDbEntityType.Create(this);

            GrowHubDbEntityType.CreateForeignKey1(growHubDb, userDb);
            GrowHubModuleDbEntityType.CreateForeignKey1(growHubModuleDb, growHubDb);
            ModuleProgramDbEntityType.CreateForeignKey1(moduleProgramDb, growHubModuleDb);
            OneTimePasswordDbEntityType.CreateForeignKey1(oneTimePasswordDb, userDb);
            PlantDbEntityType.CreateForeignKey1(plantDb, growHubDb);
            SensorReadingDbEntityType.CreateForeignKey1(sensorReadingDb, growHubDb);
            TimedQuantityDbEntityType.CreateForeignKey1(timedQuantityDb, moduleProgramDb);
            UserSessionDbEntityType.CreateForeignKey1(userSessionDb, userDb);

            GrowHubDbEntityType.CreateAnnotations(growHubDb);
            GrowHubModuleDbEntityType.CreateAnnotations(growHubModuleDb);
            ModuleProgramDbEntityType.CreateAnnotations(moduleProgramDb);
            OneTimePasswordDbEntityType.CreateAnnotations(oneTimePasswordDb);
            PlantDbEntityType.CreateAnnotations(plantDb);
            SensorReadingDbEntityType.CreateAnnotations(sensorReadingDb);
            TimedQuantityDbEntityType.CreateAnnotations(timedQuantityDb);
            UserDbEntityType.CreateAnnotations(userDb);
            UserSessionDbEntityType.CreateAnnotations(userSessionDb);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.5");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
