// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SmartGrowHub.Infrastructure.Data.CompiledModels
{
    public partial class ApplicationContextModel
    {
        private ApplicationContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("978cc1a4-1e63-4fbb-b0d9-17751fef44b0"), entityTypeCount: 12)
        {
        }

        partial void Initialize()
        {
            var growHubDb = GrowHubDbEntityType.Create(this);
            var growHubModuleDb = GrowHubModuleDbEntityType.Create(this);
            var intervalDb = IntervalDbEntityType.Create(this);
            var oneTimePasswordDb = OneTimePasswordDbEntityType.Create(this);
            var plantDb = PlantDbEntityType.Create(this);
            var scheduleDb = ScheduleDbEntityType.Create(this);
            var scheduleUnitDb = ScheduleUnitDbEntityType.Create(this);
            var quantityDb = QuantityDbEntityType.Create(this);
            var sensorReadingDb = SensorReadingDbEntityType.Create(this);
            var quantityDb0 = QuantityDb0EntityType.Create(this);
            var userDb = UserDbEntityType.Create(this);
            var userSessionDb = UserSessionDbEntityType.Create(this);

            GrowHubDbEntityType.CreateForeignKey1(growHubDb, userDb);
            GrowHubModuleDbEntityType.CreateForeignKey1(growHubModuleDb, growHubDb);
            IntervalDbEntityType.CreateForeignKey1(intervalDb, scheduleUnitDb);
            OneTimePasswordDbEntityType.CreateForeignKey1(oneTimePasswordDb, userDb);
            PlantDbEntityType.CreateForeignKey1(plantDb, growHubDb);
            ScheduleDbEntityType.CreateForeignKey1(scheduleDb, growHubModuleDb);
            ScheduleUnitDbEntityType.CreateForeignKey1(scheduleUnitDb, scheduleDb);
            QuantityDbEntityType.CreateForeignKey1(quantityDb, scheduleUnitDb);
            SensorReadingDbEntityType.CreateForeignKey1(sensorReadingDb, growHubDb);
            QuantityDb0EntityType.CreateForeignKey1(quantityDb0, sensorReadingDb);
            UserSessionDbEntityType.CreateForeignKey1(userSessionDb, userDb);

            GrowHubDbEntityType.CreateAnnotations(growHubDb);
            GrowHubModuleDbEntityType.CreateAnnotations(growHubModuleDb);
            IntervalDbEntityType.CreateAnnotations(intervalDb);
            OneTimePasswordDbEntityType.CreateAnnotations(oneTimePasswordDb);
            PlantDbEntityType.CreateAnnotations(plantDb);
            ScheduleDbEntityType.CreateAnnotations(scheduleDb);
            ScheduleUnitDbEntityType.CreateAnnotations(scheduleUnitDb);
            QuantityDbEntityType.CreateAnnotations(quantityDb);
            SensorReadingDbEntityType.CreateAnnotations(sensorReadingDb);
            QuantityDb0EntityType.CreateAnnotations(quantityDb0);
            UserDbEntityType.CreateAnnotations(userDb);
            UserSessionDbEntityType.CreateAnnotations(userSessionDb);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.5");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
