// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using SmartGrowHub.Infrastructure.Data;
using SmartGrowHub.Infrastructure.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ApplicationContext), typeof(ApplicationContextModel))]
