// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartGrowHub.Infrastructure.Data.Model;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SmartGrowHub.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class IntervalDbEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "SmartGrowHub.Infrastructure.Data.Model.IntervalDb<SmartGrowHub.Infrastructure.Data.Model.WeekTimeOnlyDb>",
                typeof(IntervalDb<WeekTimeOnlyDb>),
                baseEntityType,
                propertyCount: 2,
                navigationCount: 2,
                foreignKeyCount: 1,
                keyCount: 1);

            var timedQuantityDbModuleProgramDbId = runtimeEntityType.AddProperty(
                "TimedQuantityDbModuleProgramDbId",
                typeof(string),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            timedQuantityDbModuleProgramDbId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var timedQuantityDb__synthesizedOrdinal = runtimeEntityType.AddProperty(
                "TimedQuantityDb__synthesizedOrdinal",
                typeof(int),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            timedQuantityDb__synthesizedOrdinal.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { timedQuantityDbModuleProgramDbId, timedQuantityDb__synthesizedOrdinal });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("TimedQuantityDbModuleProgramDbId"), declaringEntityType.FindProperty("TimedQuantityDb__synthesizedOrdinal") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("ModuleProgramDbId"), principalEntityType.FindProperty("__synthesizedOrdinal") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                unique: true,
                required: true,
                requiredDependent: true,
                ownership: true);

            var interval = principalEntityType.AddNavigation("Interval",
                runtimeForeignKey,
                onDependent: false,
                typeof(IntervalDb<WeekTimeOnlyDb>),
                propertyInfo: typeof(TimedQuantityDb<WeekTimeOnlyDb>).GetProperty("Interval", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TimedQuantityDb<WeekTimeOnlyDb>).GetField("<Interval>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                eagerLoaded: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Programs");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
