// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartGrowHub.Infrastructure.Data.Model;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SmartGrowHub.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class WeekTimeOnlyDbEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "SmartGrowHub.Infrastructure.Data.Model.IntervalDb<SmartGrowHub.Infrastructure.Data.Model.WeekTimeOnlyDb>.End#WeekTimeOnlyDb",
                typeof(WeekTimeOnlyDb),
                baseEntityType,
                sharedClrType: true,
                propertyCount: 4,
                foreignKeyCount: 1,
                keyCount: 1);

            var intervalDbTimedQuantityDbModuleProgramDbId = runtimeEntityType.AddProperty(
                "IntervalDbTimedQuantityDbModuleProgramDbId",
                typeof(string),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            intervalDbTimedQuantityDbModuleProgramDbId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var intervalDbTimedQuantityDb__synthesizedOrdinal = runtimeEntityType.AddProperty(
                "IntervalDbTimedQuantityDb__synthesizedOrdinal",
                typeof(int),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            intervalDbTimedQuantityDb__synthesizedOrdinal.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var dayOfWeek = runtimeEntityType.AddProperty(
                "DayOfWeek",
                typeof(DayOfWeek),
                propertyInfo: typeof(WeekTimeOnlyDb).GetProperty("DayOfWeek", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WeekTimeOnlyDb).GetField("<DayOfWeek>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                jsonValueReaderWriter: JsonWarningEnumReaderWriter<DayOfWeek>.Instance);
            dayOfWeek.SetSentinelFromProviderValue(0);
            dayOfWeek.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var timeOnly = runtimeEntityType.AddProperty(
                "TimeOnly",
                typeof(TimeOnly),
                propertyInfo: typeof(WeekTimeOnlyDb).GetProperty("TimeOnly", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WeekTimeOnlyDb).GetField("<TimeOnly>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new TimeOnly(0, 0, 0));
            timeOnly.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { intervalDbTimedQuantityDbModuleProgramDbId, intervalDbTimedQuantityDb__synthesizedOrdinal });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("IntervalDbTimedQuantityDbModuleProgramDbId"), declaringEntityType.FindProperty("IntervalDbTimedQuantityDb__synthesizedOrdinal") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("TimedQuantityDbModuleProgramDbId"), principalEntityType.FindProperty("TimedQuantityDb__synthesizedOrdinal") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                unique: true,
                required: true,
                ownership: true);

            var end = principalEntityType.AddNavigation("End",
                runtimeForeignKey,
                onDependent: false,
                typeof(WeekTimeOnlyDb),
                propertyInfo: typeof(IntervalDb<WeekTimeOnlyDb>).GetProperty("End", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(IntervalDb<WeekTimeOnlyDb>).GetField("<End>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                eagerLoaded: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Programs");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
