// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartGrowHub.Infrastructure.Data;

#nullable disable

namespace SmartGrowHub.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260527132404_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.GrowHubDb", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GrowHubs");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.GrowHubModuleDb", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("GrowHubId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrowHubId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.ModuleProgramDb", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("GrowHubModuleId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrowHubModuleId")
                        .IsUnique();

                    b.ToTable("ModuleProgramDb");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.OneTimePasswordDb", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OneTimePasswords");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.PlantDb", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("GrowHubId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GrowHubId")
                        .IsUnique();

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.SensorReadingDb", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<byte[]>("GrowHubId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<float>("Magnitude")
                        .HasColumnType("real");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrowHubId");

                    b.ToTable("SensorReading");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.TimedQuantityDb", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Magnitude")
                        .HasColumnType("real");

                    b.Property<byte[]>("ModuleProgramId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModuleProgramId");

                    b.ToTable("TimedQuantityDb");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.UserDb", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.UserSessionDb", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("RefreshToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.GrowHubDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.UserDb", "User")
                        .WithMany("GrowHubs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.GrowHubModuleDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.GrowHubDb", "GrowHub")
                        .WithMany("Modules")
                        .HasForeignKey("GrowHubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrowHub");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.ModuleProgramDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.GrowHubModuleDb", "GrowHubModule")
                        .WithOne("Program")
                        .HasForeignKey("SmartGrowHub.Infrastructure.Data.Model.ModuleProgramDb", "GrowHubModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrowHubModule");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.OneTimePasswordDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.UserDb", "User")
                        .WithMany("OneTimePasswords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.PlantDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.GrowHubDb", "GrowHub")
                        .WithOne("Plant")
                        .HasForeignKey("SmartGrowHub.Infrastructure.Data.Model.PlantDb", "GrowHubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrowHub");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.SensorReadingDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.GrowHubDb", "GrowHub")
                        .WithMany("SensorReadings")
                        .HasForeignKey("GrowHubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrowHub");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.TimedQuantityDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.ModuleProgramDb", "ModuleProgram")
                        .WithMany("Entries")
                        .HasForeignKey("ModuleProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleProgram");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.UserSessionDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.UserDb", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.GrowHubDb", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("Plant");

                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.GrowHubModuleDb", b =>
                {
                    b.Navigation("Program")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.ModuleProgramDb", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.UserDb", b =>
                {
                    b.Navigation("GrowHubs");

                    b.Navigation("OneTimePasswords");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
