// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartGrowHub.Infrastructure.Data;

#nullable disable

namespace SmartGrowHub.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260529180040_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.GrowHubDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GrowHubs");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.GrowHubModuleDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("GrowHubId")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrowHubId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.ModuleProgramDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("GrowHubModuleId")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrowHubModuleId")
                        .IsUnique();

                    b.ToTable("ModuleProgramDb");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.OneTimePasswordDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OneTimePasswords");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.PlantDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("GrowHubId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PlantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GrowHubId")
                        .IsUnique();

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.SensorReadingDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("GrowHubId")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrowHubId");

                    b.ToTable("SensorReading");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.UserDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.UserSessionDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RefreshToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.GrowHubDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.UserDb", "User")
                        .WithMany("GrowHubs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.GrowHubModuleDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.GrowHubDb", "GrowHub")
                        .WithMany("Modules")
                        .HasForeignKey("GrowHubId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GrowHub");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.ModuleProgramDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.GrowHubModuleDb", "GrowHubModule")
                        .WithOne("Program")
                        .HasForeignKey("SmartGrowHub.Infrastructure.Data.Model.ModuleProgramDb", "GrowHubModuleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("SmartGrowHub.Infrastructure.Data.Model.QuantityDb", "ManualQuantity", b1 =>
                        {
                            b1.Property<string>("ModuleProgramDbId")
                                .HasColumnType("text");

                            b1.Property<float>("Magnitude")
                                .HasColumnType("real");

                            b1.Property<int>("Unit")
                                .HasColumnType("integer");

                            b1.HasKey("ModuleProgramDbId");

                            b1.ToTable("ModuleProgramDb");

                            b1.WithOwner()
                                .HasForeignKey("ModuleProgramDbId");
                        });

                    b.OwnsMany("SmartGrowHub.Infrastructure.Data.Model.TimedQuantityDb<SmartGrowHub.Infrastructure.Data.Model.WeekTimeOnlyDb>", "WeekTimeOnlyEntries", b1 =>
                        {
                            b1.Property<string>("ModuleProgramDbId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.HasKey("ModuleProgramDbId", "Id");

                            b1.ToTable("TimedQuantityDb<WeekTimeOnlyDb>");

                            b1.WithOwner()
                                .HasForeignKey("ModuleProgramDbId");

                            b1.OwnsOne("SmartGrowHub.Infrastructure.Data.Model.IntervalDb<SmartGrowHub.Infrastructure.Data.Model.WeekTimeOnlyDb>", "Interval", b2 =>
                                {
                                    b2.Property<string>("TimedQuantityDbModuleProgramDbId")
                                        .HasColumnType("text");

                                    b2.Property<int>("TimedQuantityDbId")
                                        .HasColumnType("integer");

                                    b2.HasKey("TimedQuantityDbModuleProgramDbId", "TimedQuantityDbId");

                                    b2.ToTable("TimedQuantityDb<WeekTimeOnlyDb>");

                                    b2.WithOwner()
                                        .HasForeignKey("TimedQuantityDbModuleProgramDbId", "TimedQuantityDbId");

                                    b2.OwnsOne("SmartGrowHub.Infrastructure.Data.Model.WeekTimeOnlyDb", "End", b3 =>
                                        {
                                            b3.Property<string>("IntervalDbTimedQuantityDbModuleProgramDbId")
                                                .HasColumnType("text");

                                            b3.Property<int>("IntervalDbTimedQuantityDbId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("DayOfWeek")
                                                .HasColumnType("integer");

                                            b3.Property<TimeOnly>("TimeOnly")
                                                .HasColumnType("time without time zone");

                                            b3.HasKey("IntervalDbTimedQuantityDbModuleProgramDbId", "IntervalDbTimedQuantityDbId");

                                            b3.ToTable("TimedQuantityDb<WeekTimeOnlyDb>");

                                            b3.WithOwner()
                                                .HasForeignKey("IntervalDbTimedQuantityDbModuleProgramDbId", "IntervalDbTimedQuantityDbId");
                                        });

                                    b2.OwnsOne("SmartGrowHub.Infrastructure.Data.Model.WeekTimeOnlyDb", "Start", b3 =>
                                        {
                                            b3.Property<string>("IntervalDbTimedQuantityDbModuleProgramDbId")
                                                .HasColumnType("text");

                                            b3.Property<int>("IntervalDbTimedQuantityDbId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("DayOfWeek")
                                                .HasColumnType("integer");

                                            b3.Property<TimeOnly>("TimeOnly")
                                                .HasColumnType("time without time zone");

                                            b3.HasKey("IntervalDbTimedQuantityDbModuleProgramDbId", "IntervalDbTimedQuantityDbId");

                                            b3.ToTable("TimedQuantityDb<WeekTimeOnlyDb>");

                                            b3.WithOwner()
                                                .HasForeignKey("IntervalDbTimedQuantityDbModuleProgramDbId", "IntervalDbTimedQuantityDbId");
                                        });

                                    b2.Navigation("End");

                                    b2.Navigation("Start");
                                });

                            b1.OwnsOne("SmartGrowHub.Infrastructure.Data.Model.QuantityDb", "Quantity", b2 =>
                                {
                                    b2.Property<string>("TimedQuantityDbModuleProgramDbId")
                                        .HasColumnType("text");

                                    b2.Property<int>("TimedQuantityDbId")
                                        .HasColumnType("integer");

                                    b2.Property<float>("Magnitude")
                                        .HasColumnType("real");

                                    b2.Property<int>("Unit")
                                        .HasColumnType("integer");

                                    b2.HasKey("TimedQuantityDbModuleProgramDbId", "TimedQuantityDbId");

                                    b2.ToTable("TimedQuantityDb<WeekTimeOnlyDb>");

                                    b2.WithOwner()
                                        .HasForeignKey("TimedQuantityDbModuleProgramDbId", "TimedQuantityDbId");
                                });

                            b1.Navigation("Interval")
                                .IsRequired();

                            b1.Navigation("Quantity")
                                .IsRequired();
                        });

                    b.OwnsMany("SmartGrowHub.Infrastructure.Data.Model.TimedQuantityDb<System.TimeOnly>", "TimeOnlyEntries", b1 =>
                        {
                            b1.Property<string>("ModuleProgramDbId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.HasKey("ModuleProgramDbId", "Id");

                            b1.ToTable("TimedQuantityDb<TimeOnly>");

                            b1.WithOwner()
                                .HasForeignKey("ModuleProgramDbId");

                            b1.OwnsOne("SmartGrowHub.Infrastructure.Data.Model.IntervalDb<System.TimeOnly>", "Interval", b2 =>
                                {
                                    b2.Property<string>("TimedQuantityDbModuleProgramDbId")
                                        .HasColumnType("text");

                                    b2.Property<int>("TimedQuantityDbId")
                                        .HasColumnType("integer");

                                    b2.Property<TimeOnly>("End")
                                        .HasColumnType("time without time zone");

                                    b2.Property<TimeOnly>("Start")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("TimedQuantityDbModuleProgramDbId", "TimedQuantityDbId");

                                    b2.ToTable("TimedQuantityDb<TimeOnly>");

                                    b2.WithOwner()
                                        .HasForeignKey("TimedQuantityDbModuleProgramDbId", "TimedQuantityDbId");
                                });

                            b1.OwnsOne("SmartGrowHub.Infrastructure.Data.Model.QuantityDb", "Quantity", b2 =>
                                {
                                    b2.Property<string>("TimedQuantityDbModuleProgramDbId")
                                        .HasColumnType("text");

                                    b2.Property<int>("TimedQuantityDbId")
                                        .HasColumnType("integer");

                                    b2.Property<float>("Magnitude")
                                        .HasColumnType("real");

                                    b2.Property<int>("Unit")
                                        .HasColumnType("integer");

                                    b2.HasKey("TimedQuantityDbModuleProgramDbId", "TimedQuantityDbId");

                                    b2.ToTable("TimedQuantityDb<TimeOnly>");

                                    b2.WithOwner()
                                        .HasForeignKey("TimedQuantityDbModuleProgramDbId", "TimedQuantityDbId");
                                });

                            b1.Navigation("Interval")
                                .IsRequired();

                            b1.Navigation("Quantity")
                                .IsRequired();
                        });

                    b.Navigation("GrowHubModule");

                    b.Navigation("ManualQuantity");

                    b.Navigation("TimeOnlyEntries");

                    b.Navigation("WeekTimeOnlyEntries");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.OneTimePasswordDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.UserDb", "User")
                        .WithMany("OneTimePasswords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.PlantDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.GrowHubDb", "GrowHub")
                        .WithOne("Plant")
                        .HasForeignKey("SmartGrowHub.Infrastructure.Data.Model.PlantDb", "GrowHubId");

                    b.Navigation("GrowHub");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.SensorReadingDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.GrowHubDb", "GrowHub")
                        .WithMany("SensorReadings")
                        .HasForeignKey("GrowHubId");

                    b.OwnsOne("SmartGrowHub.Infrastructure.Data.Model.QuantityDb", "Quantity", b1 =>
                        {
                            b1.Property<string>("SensorReadingDbId")
                                .HasColumnType("text");

                            b1.Property<float>("Magnitude")
                                .HasColumnType("real")
                                .HasColumnName("Value");

                            b1.Property<int>("Unit")
                                .HasColumnType("integer")
                                .HasColumnName("Unit");

                            b1.HasKey("SensorReadingDbId");

                            b1.ToTable("SensorReading");

                            b1.WithOwner()
                                .HasForeignKey("SensorReadingDbId");
                        });

                    b.Navigation("GrowHub");

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.UserSessionDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.UserDb", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.GrowHubDb", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("Plant");

                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.GrowHubModuleDb", b =>
                {
                    b.Navigation("Program")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.UserDb", b =>
                {
                    b.Navigation("GrowHubs");

                    b.Navigation("OneTimePasswords");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
