// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartGrowHub.Infrastructure.Data;

#nullable disable

namespace SmartGrowHub.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.GrowHubDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GrowHubs");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.GrowHubModuleDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("GrowHubId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrowHubId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.OneTimePasswordDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OneTimePasswords");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.PlantDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("GrowHubId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("PlantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GrowHubId")
                        .IsUnique();

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.ScheduleDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("GrowHubModuleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrowHubModuleId")
                        .IsUnique();

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.ScheduleUnitDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("ScheduleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("SchedulesUnits");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.SensorReadingDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrowHubId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrowHubId");

                    b.ToTable("SensorReading");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.UserDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.UserSessionDb", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RefreshToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.GrowHubDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.UserDb", "User")
                        .WithMany("GrowHubs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.GrowHubModuleDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.GrowHubDb", "GrowHub")
                        .WithMany("Modules")
                        .HasForeignKey("GrowHubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrowHub");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.OneTimePasswordDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.UserDb", "User")
                        .WithMany("OneTimePasswords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.PlantDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.GrowHubDb", "GrowHub")
                        .WithOne("Plant")
                        .HasForeignKey("SmartGrowHub.Infrastructure.Data.Model.PlantDb", "GrowHubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrowHub");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.ScheduleDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.GrowHubModuleDb", "GrowHubModule")
                        .WithOne("Schedule")
                        .HasForeignKey("SmartGrowHub.Infrastructure.Data.Model.ScheduleDb", "GrowHubModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrowHubModule");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.ScheduleUnitDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.ScheduleDb", "Schedule")
                        .WithMany("Units")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SmartGrowHub.Infrastructure.Data.Model.IntervalDb", "Interval", b1 =>
                        {
                            b1.Property<string>("ScheduleUnitDbId")
                                .HasColumnType("text");

                            b1.Property<string>("End")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Start")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ScheduleUnitDbId");

                            b1.ToTable("SchedulesUnits");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleUnitDbId");
                        });

                    b.OwnsOne("SmartGrowHub.Infrastructure.Data.Model.QuantityDb", "Quantity", b1 =>
                        {
                            b1.Property<string>("ScheduleUnitDbId")
                                .HasColumnType("text");

                            b1.Property<float>("Magnitude")
                                .HasColumnType("real");

                            b1.Property<int>("Unit")
                                .HasColumnType("integer");

                            b1.HasKey("ScheduleUnitDbId");

                            b1.ToTable("SchedulesUnits");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleUnitDbId");
                        });

                    b.Navigation("Interval")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.SensorReadingDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.GrowHubDb", "GrowHub")
                        .WithMany("SensorReadings")
                        .HasForeignKey("GrowHubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SmartGrowHub.Infrastructure.Data.Model.QuantityDb", "Quantity", b1 =>
                        {
                            b1.Property<string>("SensorReadingDbId")
                                .HasColumnType("text");

                            b1.Property<float>("Magnitude")
                                .HasColumnType("real")
                                .HasColumnName("Value");

                            b1.Property<int>("Unit")
                                .HasColumnType("integer")
                                .HasColumnName("Unit");

                            b1.HasKey("SensorReadingDbId");

                            b1.ToTable("SensorReading");

                            b1.WithOwner()
                                .HasForeignKey("SensorReadingDbId");
                        });

                    b.Navigation("GrowHub");

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.UserSessionDb", b =>
                {
                    b.HasOne("SmartGrowHub.Infrastructure.Data.Model.UserDb", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.GrowHubDb", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("Plant");

                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.GrowHubModuleDb", b =>
                {
                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.ScheduleDb", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("SmartGrowHub.Infrastructure.Data.Model.UserDb", b =>
                {
                    b.Navigation("GrowHubs");

                    b.Navigation("OneTimePasswords");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
